name: e_leaningapp
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev.

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0
  firebase_core: ^3.0.0
  file_picker: ^5.2.10
  flick_video_player: ^0.8.0
  image_picker: ^1.0.7
  get: ^4.6.6
  iconly: ^1.0.1
  flutter_dropdown_search: ^0.0.4
  shimmer: ^3.0.0
  font_awesome_flutter: ^10.7.0
  animate_do: ^3.3.4
  intl: ^0.19.0
  google_sign_in: ^6.2.1
  firebase_auth: ^5.0.0
  http: ^1.2.0
  flutter_facebook_auth: ^6.0.4
  flutter_form_builder: ^9.2.1
  video_thumbnail: ^0.5.3
  flutter_easyloading: ^3.0.5
  shared_preferences: ^2.2.3
  connectivity_plus: ^6.0.3
  internet_connection_checker_plus: ^0.0.1
  animated_text_kit: ^4.2.2
  custom_refresh_indicator: ^3.1.0
  carousel_slider: ^4.2.1
  palette_generator: ^0.3.3+3
  video_player: ^2.8.6
  better_player_plus: ^1.0.7
  path_provider: ^2.1.3
  cached_network_image: ^3.3.1
  flutter_staggered_animations: ^1.1.1
  mailer: ^6.1.0
  numeral: ^3.0.0
  image_cropper: ^7.0.5
  uuid: ^4.4.0
  colorful_progress_indicators: ^1.0.2
  vertical_scrollable_tabview: ^0.1.1
  colorful_circular_progress_indicator: ^0.0.2
  random_avatar: ^0.0.8
  flutter_svg: ^2.0.10+1
  chewie: ^1.8.1
  pull_to_refresh: ^2.0.0
  extended_nested_scroll_view: ^6.2.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
